language: perl
addons:
  apt:
    packages:
    - libssl-dev
perl:
  - "5.14"
sudo: false
install:
  - "cpanm Dist::Zilla"
  - "dzil authordeps --missing | cpanm"
  - "cpanm Bio::SeqIO Test::File::Contents Statistics::Lite File::Slurper"
script: "dzil test"
